services:
  mydb:
    image: postgres:latest
    container_name: mypostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: govinda123
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  mainapp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nextapp
    container_name: myapp
    ports:
      - "3000:3000"
    depends_on:
      mydb:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:govinda123@mypostgres:5432/postgres

  ws:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ws
    container_name: ywebrtc
    ports:
      - "4444:4444"
