name: deployment
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: build app image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest -f ./docker/Dockerfile.nextapp .
            - name: build ws image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ws:latest -f ./docker/Dockerfile.ws .
            - name: Push Docker image app
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
            - name: Push Docker image ws
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ws:latest
